In [1]:
import cv2
import numpy as np

#path = 'Images/hieroglyphs.jpg'
#path = 'Images/test.png'
#path = 'Images/egyy.png'
#path = 'Images/cover.jpg'
#path = 'Images/covercrop.jpg'
#path = 'Images/jmix.png'
#path = 'Images/hori.jpg'asc.jpg
#path = 'Images/asc.jpg'
#path = 'Images/egyptianTexts21.jpg'
#path = 'Images/unnamed.jpg'
path = 'Images/tshirt.jpg'




img1 = cv2.imread(path)
img = cv2.imread(path)
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)
imgBlur2 = cv2.GaussianBlur(imgGray,(7,7),3)
imgBlur3 = cv2.GaussianBlur(imgGray,(13,13),1)


def stackImages(scale,imgArray):
    """
    This fucntion stacks images. However, I did not build it.
    Recovered from: https://www.youtube.com/watch?v=WQeoO7MI0Bs
    To work properly, you should have rectangles (equal number
    of imgs per column or row)
    """
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver


#define kernel 
kernel = np.ones((3,3),np.uint8)

imgCanny = cv2.Canny(imgBlur,50,50)
imgDialation = cv2.dilate(imgCanny,kernel,iterations=1)
imgDialation2 = cv2.dilate(imgCanny,kernel,iterations=5)
imgEroded = cv2.erode(imgCanny,kernel,iterations=1)

imgCanny2 = cv2.Canny(imgBlur,150,200)
imgDialationX = cv2.dilate(imgCanny2,kernel,iterations=1)

imgCanny3 = cv2.Canny(imgBlur,10,30)

imgBlank= np.zeros_like(img)





def getContours(img):
    contours,hierarchy = cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        print(area)
        if area>150:
                    cv2.drawContours(imgContour,cnt,-1,(255,0,0),3)
                    peri = cv2.arcLength(cnt,True)
                    print(peri)
                    approx = cv2.approxPolyDP(cnt,0.02*peri,True)
                    print(len(approx))
                    objCor = len(approx)
                    x,y,w,h = cv2.boundingRect(approx)
                    
                    cv2.rectangle(imgContour,(x,y),(x+w,y+h),(0,255,0),2)
                    
                    
                    
                    
                    
                    
                    
def getContours1(img):
    xox=1
    contours,hierarchy = cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        print(area)
        if area>300:
                    xox=xox+1
                    cv2.drawContours(imgContour1,cnt,-1,(255,0,0),3)
                    peri = cv2.arcLength(cnt,True)
                    print(peri)
                    approx = cv2.approxPolyDP(cnt,0.02*peri,True)
                    print(len(approx))
                    objCor = len(approx)
                    x,y,w,h = cv2.boundingRect(approx)
                    
                    cv2.rectangle(imgContour1,(x,y),(x+w,y+h),(0,255,0),2)
                    
                    cropped_Contour = img1[y: y + h, x: x + w]
                    image_Name = "cnt" + str(x) + ".jpg"
                    #print (image_Name)
                    cv2.imwrite(image_Name, cropped_Contour)
                    
                    

                
imgContour = img.copy()
imgContour1 = img.copy()

output_Images=[]

getContours(imgCanny)
getContours1(imgDialationX)
imgStack= stackImages(0.2,([img,imgBlur,imgBlank],[imgCanny,imgContour,imgContour1 ]))
cv2.imshow("stack",imgStack)

cv2.waitKey(0)
cv2.destroyAllWindows()

0.0
0.0
858.5
122.5269113779068
6
0.0
0.0
0.5
0.0
0.0
548.0
112.76955199241638
5
0.0
0.0
1.0
9797.0
412.04877042770386
6
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
825.5
141.63960921764374
8
0.0
439.5
2095.201345562935
9
1.0
8848.0
481.8477599620819
9
0.0
231.5
1943.0550342798233
13
11830.5
707.4041088819504
5
9011.0
542.1076455116272
5
4446.0
894.9604578018188
7
0.0
0.0
0.0
0.0
1.0
0.5
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
77.0
0.0
0.0
6031.0
1762.0184564590454
14
0.0
0.0
0.0
1378.5
173.5807341337204
6
5344.5
363.546244263649
7
1509.5
196.95331752300262
9
0.0
0.0
167.5
1545.550420165062
11
0.0
0.0
0.0
0.0
1487.5
191.78174459934235
7
7765.5
460.6000670194626
7
0.0
4994.0
345.3036036491394
7
0.5
73.5
0.0
9294.0
491.24472856521606
8
6812.0
416.0731556415558
8
2473.5
313.722869515419
7
0.0
16726.5
570.0315254926682
6
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
16898.5
565.6883796453476
6
0.5
0.0
0.0
0.0
105.5
0.0
0.0
0.0
0.0
0.0
0.0
3.5
0.0
7955.0
485.64674949645996
7
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5
0.0
0

In [24]:
import cv2
import numpy as np

path = 'Images/geek.jpg'
img = cv2.imread(path)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
for rho,theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imwrite('houghlines3.jpg',img)

True

In [23]:
import cv2
import numpy as np
path = 'Images/geek.jpg'
img = cv2.imread(path)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)
minLineLength = 100
maxLineGap = 10
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength,maxLineGap)
for x1,y1,x2,y2 in lines[0]:
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('houghlines5.jpg',img)

True

In [22]:
import numpy as np
import cv2

path = 'Images/geek.jpg'
img = cv2.imread(path)
edges = cv2.Canny(gray,50,150,apertureSize = 3)
cv2.imwrite('edges-50-150.jpg',edges)
minLineLength=100
lines = cv2.HoughLinesP(image=edges,rho=1,theta=np.pi/180, threshold=100,lines=np.array([]), minLineLength=minLineLength,maxLineGap=80)

a,b,c = lines.shape
for i in range(a):
    cv2.line(gray, (lines[i][0][0], lines[i][0][1]), (lines[i][0][2], lines[i][0][3]), (0, 0, 255), 3, cv2.LINE_AA)
    cv2.imwrite('houghlines5.jpg',gray)

rho -> dstance resolution of the accumlator in pixels
theta -> angle resolution in accumlator in radians
threshold -> Accumlator threshold parameter . only those lines are returned that get enough votes (.threshold)

In [21]:
import cv2
import numpy as np
path = 'Images/geek.jpg'
img = cv2.imread(path)

kernel = np.ones((3,3),np.uint8)

imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)
imgCanny2 = cv2.Canny(imgBlur,150,200)
imgDialationX = cv2.dilate(imgCanny2,kernel,iterations=1)





cv2.imshow("images",imgDialationX)


minLineLength=500
maxLineGap=80
lines = cv2.HoughLinesP(image=imgDialationX,rho=1,theta=np.pi/180, threshold=10,lines=np.array([]), minLineLength=minLineLength,maxLineGap=maxLineGap)

for line in lines:
    x1,y1,x2,y2 = line[0]
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    
cv2.imshow("stack",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:


import cv2
import numpy as np

path = 'Images/geek.jpg'
#path = 'Images/hieroglyphs.jpg'
#path = 'Images/test.png'
#path = 'Images/egyy.png'
#path = 'Images/cover.jpg'
#path = 'Images/covercrop.jpg'
#path = 'Images/jmix.png'
#path = 'Images/hori.jpg'
#path = 'Images/asc.jpg'
#path = 'Images/egyptianTexts21.jpg'
#path = 'Images/tshirt.jpg'


img = cv2.imread(path)
ret,img = cv2.threshold(img,180,255,0)

element = cv2.getStructuringElement(cv2.MORPH_CROSS,(6,6))
eroded = cv2.erode(img,element)
dilate = cv2.dilate(eroded, element)
skeleton = cv2.subtract(img, dilate)
gray = cv2.cvtColor(skeleton,cv2.COLOR_BGR2GRAY)

minLineLength = 20
maxLineGap = 1

lines = cv2.HoughLinesP(gray, 1, np.pi/180, 10, minLineLength, maxLineGap)

for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow("result", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(len(lines))

7388


In [20]:
import cv2
import numpy as np
path = 'Images/geek.jpg'
img = cv2.imread(path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 80, 120)
lines = cv2.HoughLinesP(edges, 1, np.pi/2, 2, None, 30, 1);
for line in lines[0]:
    pt1 = (line[0],line[1])
    pt2 = (line[2],line[3])
    cv2.line(img, pt1, pt2, (0,0,255), 3)
cv2.imwrite("2.png", img)

True

In [19]:
# Python program to illustrate HoughLine 
# method for line detection 
import cv2 
import numpy as np 
  
# Reading the required image in  
# which operations are to be done.  
# Make sure that the image is in the same  
# directory in which this python program is 

path = 'Images/geek.jpg'
img = cv2.imread(path)

  
# Convert the img to grayscale 
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) 
  
# Apply edge detection method on the image 
edges = cv2.Canny(gray,50,150,apertureSize = 3) 
  
# This returns an array of r and theta values 
lines = cv2.HoughLines(edges,1,np.pi/180, 10) 
  
# The below for loop runs till r and theta values  
# are in the range of the 2d array 
for r,theta in lines[0]: 
      
    # Stores the value of cos(theta) in a 
    a = np.cos(theta) 
  
    # Stores the value of sin(theta) in b 
    b = np.sin(theta) 
      
    # x0 stores the value rcos(theta) 
    x0 = a*r 
      
    # y0 stores the value rsin(theta) 
    y0 = b*r 
      
    # x1 stores the rounded off value of (rcos(theta)-1000sin(theta)) 
    x1 = int(x0 + 1000*(-b)) 
      
    # y1 stores the rounded off value of (rsin(theta)+1000cos(theta)) 
    y1 = int(y0 + 1000*(a)) 
  
    # x2 stores the rounded off value of (rcos(theta)+1000sin(theta)) 
    x2 = int(x0 - 1000*(-b)) 
      
    # y2 stores the rounded off value of (rsin(theta)-1000cos(theta)) 
    y2 = int(y0 - 1000*(a)) 
      
    # cv2.line draws a line in img from the point(x1,y1) to (x2,y2). 
    # (0,0,255) denotes the colour of the line to be  
    #drawn. In this case, it is red.  
    cv2.line(img,(x1,y1), (x2,y2), (0,0,255),2) 
      
# All the changes made in the input image are finally 
# written on a new image houghlines.jpg 
cv2.imwrite('linesDetected.jpg', img) 

True

In [7]:


import numpy as np
import cv2 as cv2
import math
#Sobel Function for edge detection
def sobel(img,x_kernel,y_kernel):
    gx=np.zeros(img.shape)
    gy=np.zeros(img.shape)
    x_image = np.pad(img, pad_width=1, mode='constant', constant_values=0)
    rows=len(x_image)
    cols=len(x_image[0])
    krows=len(x_kernel)
    kcols=len(x_kernel[0])
    for i in range(rows-2):
        for j in range(cols-2):
            result=0
            for r in range(krows):
                for c in range(kcols):
                    result=result+(x_image[i+r][j+c]*x_kernel[r][c])
            gx[i][j]=result

    y_image = np.pad(img, pad_width=1, mode='constant', constant_values=0)
    for i in range(rows-2):
        for j in range(cols-2):
            result=0
            for r in range(krows):
                for c in range(kcols):
                    result=result+(y_image[i+r][j+c]*y_kernel[r][c])
            gy[i][j]=result

    g=np.sqrt(np.add(np.square(gx),np.square(gy)))
    g[g<0]=0
    g[g>255]=255
    g=g.astype(np.uint8)
    return g

#Reading the image and applying edge detection functions
img = cv2.imread('hough.jpg',0)

x_kernel_edge=[[-1,0,1],[-2,0,2],[-1,0,1]]
y_kernel_edge=[[1,2,1],[0,0,0],[-1,-2,-1]]
edge_detection_edge=sobel(img,x_kernel_edge,y_kernel_edge)
x_kernel_diag=[[0,1,2],[-1,0,1],[-2,-1,0]]
y_kernel_diag=[[-2,-1,0],[-1,0,1],[0,1,2]]
edge_detection_diag=sobel(img,x_kernel_diag,y_kernel_diag)
edge_detection=np.maximum(edge_detection_edge,edge_detection_diag)
####Used canny only for testing#####
#edge_detection = cv2.Canny(img,50,150,apertureSize = 3)
cv2.imwrite('edges_detected.jpg',edge_detection)
#######Defining the rho and theta values #######
w, h = img.shape
len_diag = np.ceil(np.sqrt(w * w + h * h))   # max_dist
rhos = np.linspace(-len_diag, len_diag, len_diag * 2.0)
rhos=np.asarray(rhos)
n_rho=len(rhos)
thetas = np.deg2rad(np.arange(0, 181))
n_theta=len(thetas)

#Defining Parameter space for Hough Space
P=np.zeros((n_rho,n_theta))
##For each edge point, finding the corresponding rho value for each theta and storing
#Votes in the Parameter matrix
for i in range(len(edge_detection)):
    for j in range(len(edge_detection[0])):
        if(edge_detection[i][j]>100):
            for theta in range(n_theta):
                rho = int(round((j * (np.cos(thetas[theta])) + i * (np.sin(thetas[theta])))+len_diag))
                P[rho, theta] =P[rho, theta]+ 1
#Taking the indices which have received the maximum votes
max_vote_index=np.argwhere(P>270)
##Forming a list of rho, theta pairs which have received maximum votes
rho_theta=[]
for i in range(len(max_vote_index)):
    rho_theta.append([rhos[max_vote_index[i][0]],thetas[max_vote_index[i][1]]])
rho_theta=np.asarray(rho_theta)

#drawing red vertical lines in green
img_c= cv2.imread('hough.jpg')
for i in range(len(rho_theta)):
    if(math.degrees(rho_theta[i][1])in range(160,181)):
        a = np.cos(rho_theta[i][1])
        b = np.sin(rho_theta[i][1])
        x0 = a*rho_theta[i][0]
        y0 = b*rho_theta[i][0]
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))
        cv2.line(img_c,(x1,y1),(x2,y2),(0,255,0),2)
cv2.imwrite('red_line.jpg',img_c)

#Taking the indices which have received the maximum votes for blue lines
max_vote_index=np.argwhere(P>205)
##Forming a list of rho, theta pairs which have received maximum votes
rho_theta=[]
for i in range(len(max_vote_index)):
    rho_theta.append([rhos[max_vote_index[i][0]],thetas[max_vote_index[i][1]]])
rho_theta=np.asarray(rho_theta)
#drawing blue lines in green
img_c= cv2.imread('hough.jpg')
for i in range(len(rho_theta)):
    if(math.degrees(rho_theta[i][1])in range(144,146)):
        a = np.cos(rho_theta[i][1])
        b = np.sin(rho_theta[i][1])
        x0 = a*rho_theta[i][0]
        y0 = b*rho_theta[i][0]
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))
        cv2.line(img_c,(x1,y1),(x2,y2),(0,255,0),2)
cv2.imwrite('blue_lines.jpg',img_c)

True

threshold, which means the minimum vote it should get to be considered as a line.
return -> (x1,y1,x2,y2)
maxLineGap -> Maximum allowed gap between points on the same line to link them.

In [7]:
import cv2
import numpy as np

img = cv2.imread("2.png")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,210,apertureSize = 3)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
for rho,theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imwrite('houghlines3.jpg',img)

True

In [2]:
import cv2
import numpy as np
path = 'Images/geek.jpg'
img = cv2.imread(path, cv2.IMREAD_COLOR)


# Convert the image to gray-scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Find the edges in the image using canny detector
edges = cv2.Canny(gray, 50, 200)
# Detect points that form a line
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100,np.array ([ ]), minLineLength=((img.shape[0])/2), maxLineGap=10)
# Draw lines on the image
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(img, (x1, y1), (x2, y2), (255, 0, 0), 2)

# Show result
cv2.imshow("Result Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
tryAll= [[[0,0,0,0]]]
if(tryAll.all()!=None):print('zby')

AttributeError: 'list' object has no attribute 'all'

In [3]:

import cv2
import numpy as np

#path = 'Images/geek.jpg'
#path = 'Images/hieroglyphs.jpg'
#path = 'Images/test.png'
#path = 'Images/egyy.png'
#path = 'Images/cover.jpg'
#path = 'Images/covercrop.jpg'
#path = 'Images/jmix.png'
path = 'Images/hori.jpg'
#path = 'Images/asc.jpg'
#ath = 'Images/egyptianTexts21.jpg'
#path = 'Images/tshirt.jpg'


img = cv2.imread(path)

#print(img.shape[0])

kernel = np.ones((3,3),np.uint8)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,210,apertureSize = 3)
#imgBlur = cv2.GaussianBlur(gray,(7,7),1)
#imgCanny2 = cv2.Canny(gray,100,100)
imgDialationX = cv2.dilate(edges,kernel,iterations=1)
minLineLength = (np.minimum(img.shape[0],img.shape[1]))/2
maxLineGap = 5
#np.array([])
lines = cv2.HoughLinesP(imgDialationX,1,np.pi/180,300, 100000,minLineLength,maxLineGap)
try:
    if len(lines) != 0 :
        for line in lines:
            x1,y1,x2,y2 =line[0]
            cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

        linescpy = lines
        '''for line0 in linescpy:
            for line1 in linescpy:
                line01cpy=line0 - line1
                #print (line01cpy)
                if(line01cpy[0]<20):
                    print('haha')'''
        imS = cv2.resize(img, (960, 540))   
        cv2.imshow("Result Image",imS)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        cv2.imwrite('newlines69.jpeg',img)
        print(len(lines))
        print(lines)
        
except:
    pass



84
[[[  0 704 799 704]]

 [[  0 437 799 437]]

 [[  0 523 799 523]]

 [[  0 702 799 702]]

 [[  0 705 799 705]]

 [[  0  83 799  83]]

 [[  0   3 799   3]]

 [[  0 625 799 625]]

 [[  0 703 799 703]]

 [[  0 534 799 534]]

 [[  0 170 799 170]]

 [[  0 791 799 791]]

 [[  0 615 799 615]]

 [[  0 713 799 713]]

 [[  0 525 799 525]]

 [[  0 439 799 439]]

 [[  0 176 799 176]]

 [[  0 180 799 180]]

 [[  0 355 799 355]]

 [[  0 701 799 701]]

 [[  0  87 799  87]]

 [[  0 790 799 790]]

 [[  0 793 799 793]]

 [[  0 348 799 348]]

 [[  0 712 799 712]]

 [[  0 623 799 623]]

 [[  0 350 799 350]]

 [[  0 613 799 613]]

 [[  0 177 799 177]]

 [[  0 624 799 624]]

 [[  0 258 799 258]]

 [[  0 447 799 447]]

 [[  0 443 799 443]]

 [[  0 358 799 358]]

 [[  0 169 799 169]]

 [[  0 357 799 357]]

 [[  0 269 799 269]]

 [[  0 259 799 259]]

 [[  0 356 799 356]]

 [[  0 438 799 438]]

 [[  0  79 799  79]]

 [[  0 532 799 532]]

 [[  0 435 799 435]]

 [[  0  89 799  89]]

 [[  0 436 799 436]]

 [[  0 

In [4]:
#class by banderlog013 on stackoverflow
#https://stackoverflow.com/a/50389879/14263835
class HoughBundler:
    '''Clasterize and merge each cluster of cv2.HoughLinesP() output
    a = HoughBundler()
    foo = a.process_lines(houghP_lines, binary_image)
    '''

    def get_orientation(self, line):
        '''get orientation of a line, using its length
        https://en.wikipedia.org/wiki/Atan2
        '''
        orientation = math.atan2(abs((line[0] - line[2])), abs((line[1] - line[3])))
        return math.degrees(orientation)

    def checker(self, line_new, groups, min_distance_to_merge, min_angle_to_merge):
        '''Check if line have enough distance and angle to be count as similar
        '''
        for group in groups:
            # walk through existing line groups
            for line_old in group:
                # check distance
                if self.get_distance(line_old, line_new) < min_distance_to_merge:
                    # check the angle between lines
                    orientation_new = self.get_orientation(line_new)
                    orientation_old = self.get_orientation(line_old)
                    # if all is ok -- line is similar to others in group
                    if abs(orientation_new - orientation_old) < min_angle_to_merge:
                        group.append(line_new)
                        return False
        # if it is totally different line
        return True

    def DistancePointLine(self, point, line):
        """Get distance between point and line
        http://local.wasp.uwa.edu.au/~pbourke/geometry/pointline/source.vba
        """
        px, py = point
        x1, y1, x2, y2 = line

        def lineMagnitude(x1, y1, x2, y2):
            'Get line (aka vector) length'
            lineMagnitude = math.sqrt(math.pow((x2 - x1), 2) + math.pow((y2 - y1), 2))
            return lineMagnitude

        LineMag = lineMagnitude(x1, y1, x2, y2)
        if LineMag < 0.00000001:
            DistancePointLine = 9999
            return DistancePointLine

        u1 = (((px - x1) * (x2 - x1)) + ((py - y1) * (y2 - y1)))
        u = u1 / (LineMag * LineMag)

        if (u < 0.00001) or (u > 1):
            #// closest point does not fall within the line segment, take the shorter distance
            #// to an endpoint
            ix = lineMagnitude(px, py, x1, y1)
            iy = lineMagnitude(px, py, x2, y2)
            if ix > iy:
                DistancePointLine = iy
            else:
                DistancePointLine = ix
        else:
            # Intersecting point is on the line, use the formula
            ix = x1 + u * (x2 - x1)
            iy = y1 + u * (y2 - y1)
            DistancePointLine = lineMagnitude(px, py, ix, iy)

        return DistancePointLine

    def get_distance(self, a_line, b_line):
        """Get all possible distances between each dot of two lines and second line
        return the shortest
        """
        dist1 = self.DistancePointLine(a_line[:2], b_line)
        dist2 = self.DistancePointLine(a_line[2:], b_line)
        dist3 = self.DistancePointLine(b_line[:2], a_line)
        dist4 = self.DistancePointLine(b_line[2:], a_line)

        return min(dist1, dist2, dist3, dist4)

    def merge_lines_pipeline_2(self, lines):
        'Clusterize (group) lines'
        groups = []  # all lines groups are here
        # Parameters to play with
        min_distance_to_merge = 30
        min_angle_to_merge = 30
        # first line will create new group every time
        groups.append([lines[0]])
        # if line is different from existing gropus, create a new group
        for line_new in lines[1:]:
            if self.checker(line_new, groups, min_distance_to_merge, min_angle_to_merge):
                groups.append([line_new])

        return groups

    def merge_lines_segments1(self, lines):
        """Sort lines cluster and return first and last coordinates
        """
        orientation = self.get_orientation(lines[0])

        # special case
        if(len(lines) == 1):
            return [lines[0][:2], lines[0][2:]]

        # [[1,2,3,4],[]] to [[1,2],[3,4],[],[]]
        points = []
        for line in lines:
            points.append(line[:2])
            points.append(line[2:])
        # if vertical
        if 45 < orientation < 135:
            #sort by y
            points = sorted(points, key=lambda point: point[1])
        else:
            #sort by x
            points = sorted(points, key=lambda point: point[0])

        # return first and last point in sorted group
        # [[x,y],[x,y]]
        return [points[0], points[-1]]

    def process_lines(self, lines, img):
        '''Main function for lines from cv.HoughLinesP() output merging
        for OpenCV 3
        lines -- cv.HoughLinesP() output
        img -- binary image
        '''
        lines_x = []
        lines_y = []
        # for every line of cv2.HoughLinesP()
        for line_i in [l[0] for l in lines]:
                orientation = self.get_orientation(line_i)
                # if vertical
                if 45 < orientation < 135:
                    lines_y.append(line_i)
                else:
                    lines_x.append(line_i)

        lines_y = sorted(lines_y, key=lambda line: line[1])
        lines_x = sorted(lines_x, key=lambda line: line[0])
        merged_lines_all = []

        # for each cluster in vertical and horizantal lines leave only one line
        for i in [lines_x, lines_y]:
                if len(i) > 0:
                    groups = self.merge_lines_pipeline_2(i)
                    merged_lines = []
                    for group in groups:
                        merged_lines.append(self.merge_lines_segments1(group))

                    merged_lines_all.extend(merged_lines)

        return merged_lines_all
    
    
    def chk_L_V(x1,y1,x2,y2):
    X=x2-x1
    Y=y2-y1
    if(-30<X<30):
        return True
    elif(-30<Y<30):
        return False
    
    
    def chk_I_V(linesArray):
    v=0
    h=0
    for line in linesArray:
        x1,y1 =line[0]
        x2,y2=line[1]
        if self.chk_L_V(x1,y1,x2,y2):
            v=v+1
        else:
            h=h+1
    return(v>h)


    def completeLines(linesArray,img):
        isVertical=self.chk_I_V(linesArray)
        arr=[]
        if isVertical:
            for line in linesArray:
                x1,y1 =line[0]
                x2,y2=line[1]
                if(self.chk_L_V(x1,y1,x2,y2)):
                    y1=0
                    y2=img.shape[0]
                    arr.append([x1,y1,x2,y2])
        if (isVertical==False):
            for line in linesArray:
                x1,y1 =line[0]
                x2,y2=line[1]
                if(self.chk_L_V(x1,y1,x2,y2)==False):
                    x1=0
                    x2=img.shape[1]
                    arr.append([x1,y1,x2,y2])
        return arr

In [5]:
import math

a = HoughBundler()
foo = a.process_lines(lines, imgDialationX)
print(len(foo))

10


In [6]:
def chk_L_V(x1,y1,x2,y2):
    X=x2-x1
    Y=y2-y1
    if(-30<X<30):
        return True
    elif(-30<Y<30):
        return False

In [ ]:
def getCropPoints()

In [48]:
path = 'Images/jmix.png'
img = cv2.imread(path)
x=1
for line in foo:
    x1,y1 =line[0]
    x2,y2=line[1]
    #print(x1,y1,x2,y2)
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    crop_img = img[y1:y2, x1:x2]
    cv2.imshow("cropped", crop_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [7]:
def chk_I_V(linesArray):
    v=0
    h=0
    for line in linesArray:
        x1,y1 =line[0]
        x2,y2=line[1]
        if chk_L_V(x1,y1,x2,y2):
            v=v+1
        else:
            h=h+1
    return(v>h)
    

In [82]:
print(chk_I_V(foo))

False


In [8]:
def completeL(linesArray,img):
    isVertical=chk_I_V(linesArray)
    arr=[]
    if isVertical:
        for line in linesArray:
            print("isV")
            x1,y1 =line[0]
            x2,y2=line[1]
            if(chk_L_V(x1,y1,x2,y2)):
                y1=0
                y2=img.shape[0]
                arr.append([x1,y1,x2,y2])
    if (isVertical==False):
        print("isH")
        for line in linesArray:
            print('ok')
            x1,y1 =line[0]
            x2,y2=line[1]
            if(chk_L_V(x1,y1,x2,y2)==False):
                x1=0
                x2=img.shape[1]
                arr.append([x1,y1,x2,y2])
    return arr
        
                
                

In [106]:
print(completeL(foo,img))

isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
[[0, 1, 800, 3], [0, 79, 800, 91], [0, 168, 800, 180], [0, 257, 800, 269], [0, 345, 800, 358], [0, 434, 800, 447], [0, 523, 800, 536], [0, 612, 800, 625], [0, 701, 800, 714], [0, 790, 800, 794]]


In [102]:
fpp=[]
for i in range (1,10):
    fpp.append([1,2,3])
print(fpp)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [107]:
cv2.imshow("Result Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

#path = 'Images/hieroglyphs.jpg'
#path = 'Images/test.png'
#path = 'Images/egyy.png'
#path = 'Images/cover.jpg'
#path = 'Images/covercrop.jpg'
#path = 'Images/jmix.png'
path = 'Images/hori.jpg'
#path = 'Images/asc.jpg'
#path = 'Images/egyptianTexts21.jpg'
#path = 'Images/unnamed.jpg'
#path = 'Images/tshirt.jpg'




img1 = cv2.imread(path)
img = cv2.imread(path)
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)
imgBlur2 = cv2.GaussianBlur(imgGray,(7,7),3)
imgBlur3 = cv2.GaussianBlur(imgGray,(13,13),1)


def stackImages(scale,imgArray):
    """
    This fucntion stacks images. However, I did not build it.
    Recovered from: https://www.youtube.com/watch?v=WQeoO7MI0Bs
    To work properly, you should have rectangles (equal number
    of imgs per column or row)
    """
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver


#define kernel 
kernel = np.ones((3,3),np.uint8)

imgCanny = cv2.Canny(imgBlur,50,50)
imgDialation = cv2.dilate(imgCanny,kernel,iterations=1)
imgDialation2 = cv2.dilate(imgCanny,kernel,iterations=5)
imgEroded = cv2.erode(imgCanny,kernel,iterations=1)

imgCanny2 = cv2.Canny(imgBlur,150,200)
imgDialationX = cv2.dilate(imgCanny2,kernel,iterations=1)

imgCanny3 = cv2.Canny(imgBlur,10,30)

imgBlank= np.zeros_like(img)





def getContours(img):
    contours,hierarchy = cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        print(area)
        if area>150:
                    cv2.drawContours(imgContour,cnt,-1,(255,0,0),3)
                    peri = cv2.arcLength(cnt,True)
                    print(peri)
                    approx = cv2.approxPolyDP(cnt,0.02*peri,True)
                    print(len(approx))
                    objCor = len(approx)
                    x,y,w,h = cv2.boundingRect(approx)
                    
                    cv2.rectangle(imgContour,(x,y),(x+w,y+h),(0,255,0),2)
                    
                    
                    
                    
                    
                    
                    
def getContours1(img):
    contourArr=[]
    xox=1
    cCoord=[]
    contours,hierarchy = cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        print(area)
        if area>300:
                    xox=xox+1
                    #cv2.drawContours(imgContour1,cnt,-1,(255,0,0),3)
                    peri = cv2.arcLength(cnt,True)
                    #print(peri)
                    approx = cv2.approxPolyDP(cnt,0.02*peri,True)
                    #print(len(approx))
                    objCor = len(approx)
                    x,y,w,h = cv2.boundingRect(approx)
                    cCoordMidX=(x-(0.5*w))
                    cCoordMidY=(y-(0.5*h))
                    cDist=np.sqrt(np.square(cCoordMidX)+np.square(cCoordMidY))
                    
                    contourArr.append([cDist,x,y,w,h,cCoordMidX,cCoordMidY])
                    
                    ##cv2.rectangle(imgContour1,(x,y),(x+w,y+h),(0,255,0),2)
                    
                    ##cropped_Contour = img1[y: y + h, x: x + w]
                    ##image_Name = "cnt" + str(x) + ".jpg"
                    #print (image_Name)
                    ##cv2.imwrite(image_Name, cropped_Contour)
    contourArr2=np.array(contourArr)
    sortedArr = contourArr2[contourArr2[:,0].argsort()]                
    print(sortedArr)
    orderAlph=0
    for sCnt in sortedArr:
        orderAlph=orderAlph+1
        cDist,x,y,w,h,cCoordMidX,cCoordMidY =sCnt
        print("x=",x,"y=",y)
        x=np.int64(x)
        y=np.int64(y)
        w=np.int64(w)
        h=np.int64(h)
        cv2.rectangle(imgContour1,(x,y),(x+w,y+h),(0,255,0),2)
        cropped_Contour = img1[y: y + h, x: x + w]
        LinesW=completeL(foo,img)
        enumu=1
        
        if(chk_I_V(foo)):
            '''for line in LinesW:
                x1,y1,x2,y2 =line
                if(cCoordMidX>x1):enumu=enumu+1'''
                        
        elif(chk_I_V(foo)==False):
            for line in LinesW:
                x1,y1,x2,y2 =line
                if(cCoordMidY>y1):enumu=enumu+1
                        
        image_Name = "L" + str(enumu) +"Q"+str(orderAlph)+ ".jpg"
        print (image_Name)
        cv2.imwrite(image_Name, cropped_Contour)            
                    

                
imgContour = img.copy()
imgContour1 = img.copy()

output_Images=[]

getContours(imgCanny)
getContours1(imgDialationX)
imgStack= stackImages(0.2,([img,imgBlur,imgBlank],[imgCanny,imgContour,imgContour1 ]))
cv2.imshow("stack",imgStack)

cv2.waitKey(0)
cv2.destroyAllWindows()

0.0
0.0
0.0
0.0
21.5
10.5
4.5
219.5
60.38477599620819
7
0.0
0.0
0.0
435.0
159.25483322143555
7
628.5
133.8406196832657
9
1117.5
155.0710676908493
4
15.0
810.0
130.911687374115
7
637.0
135.94112491607666
8
0.0
224.0
60.97056245803833
7
223.0
60.97056245803833
7
6.0
38.0
38.0
37.0
27.5
21.0
228.5
91.89949476718903
6
217.5
91.0710676908493
8
232.0
92.48528122901917
6
15.5
2.0
4.0
0.0
0.0
0.0
0.0
14.0
0.0
1452.5
304.7523070573807
12
1.5
0.0
0.0
361.0
117.11269783973694
11
352.0
172.28427076339722
8
588.0
121.5979790687561
9
250.0
125.65685415267944
6
48.0
321.0
128.28427076339722
10
457.5
140.32590091228485
9
61.0
269.0
123.4558436870575
8
386.0
111.4558436870575
6
428.5
175.2132030725479
9
195.0
53.455843687057495
8
1.0
0.0
0.0
2.0
7.0
115.5
89.5
8.5
899.0
156.42640614509583
3
343.5
127.69848430156708
12
171.0
91.31370830535889
5
20.0
286.0
142.71067690849304
4
1577.0
170.1421353816986
4
0.0
149.0
550.0
148.56854152679443
7
897.5
200.40916121006012
11
578.0
183.7401144504547
7
549.0
144.9

x= 158.0 y= 10.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L1Q7.jpg
x= 174.0 y= 100.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L2Q8.jpg
x= 1.0 y= 188.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q9.jpg
x= 65.0 y= 188.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q10.jpg
x= 192.0 y= 10.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L1Q11.jpg
x= 192.0 y= 49.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L2Q12.jpg
x= 65.0 y= 188.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L4Q13.jpg
x= 117.0 y= 188.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L4Q14.jpg
x= 188.0 y= 141.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q15.jpg
x= 245.0 y= 22.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L1Q16.jpg
x= 179.0 y= 187.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q17.jpg
x= 246.0 y= 105.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L2Q18.jpg
x= 116.0 y= 228.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L4Q19.jpg
x= 211.0 y= 187.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q20.jpg
x= 252.0 y= 10.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L1Q21.jpg
x= 3.0 y= 278.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L4Q22.jpg
x= 294.0 y= 30.0
isH
o

x= 3.0 y= 722.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L9Q169.jpg
x= 719.0 y= 98.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q170.jpg
x= 653.0 y= 324.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L5Q171.jpg
x= 132.0 y= 723.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L9Q172.jpg
x= 159.0 y= 722.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L9Q173.jpg
x= 720.0 y= 115.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L3Q174.jpg
x= 77.0 y= 733.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L10Q175.jpg
x= 94.0 y= 721.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L10Q176.jpg
x= 118.0 y= 734.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L10Q177.jpg
x= 683.0 y= 277.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L5Q178.jpg
x= 620.0 y= 402.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L6Q179.jpg
x= 34.0 y= 735.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L10Q180.jpg
x= 0.0 y= 612.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L8Q181.jpg
x= 215.0 y= 737.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L10Q182.jpg
x= 0.0 y= 620.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L9Q183.jpg
x= 743.0 y= 200.0
isH
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
L4Q184.j

In [109]:
np.sqrt(2*np.square(3))

4.242640687119285